= Usage of the Plugin
:toc:
:sectnums:

== Overview

After the installation of the Plugin, a new category named "SimHub" will be available in Stream Deck. Use the actions of this category to get Stream Deck buttons, which will interact with SimHub, e.g. update their state from SimHub properties.


== Generic Button

See link:generic-button/GenericButton.adoc[GenericButton.adoc]

Note: This is a new button that exists since version 2.0 of the plugin. If unsure, use this button — the "old" ones below won't receive any updates anymore. This new button combines (almost) all features of the old buttons, works with Stream Deck keys and Stream Deck dials, and adds a bunch of new features.


== Hotkey

See link:hotkey/Hotkey.adoc[Hotkey.adoc]


== Flags

See link:flags/Flags.adoc[Flags.adoc]


== Hotkey 4-state

See link:hotkey-4-state/Hotkey-4-state.adoc[Hotkey-4-state.adoc]


== Input Trigger

See link:inputtrigger/InputTrigger.adoc[InputTrigger.adoc]


== Dial (Stream Deck Plus only)

See link:dial/Dial.adoc[Dial.adoc]


== ShakeIt Features

See link:shakeit/ShakeIt.adoc[ShakeIt.adoc]
