= Action "Hotkey 4-state"
:toc:
:sectnums:
ifdef::env-github[]
:tip-caption: :bulb:
endif::[]
ifndef::env-github[]
:tip-caption: 💡
endif::[]

TIP: Always read the *correct version* of the documentation, which matches the version of the plugin that you have installed. To do so, use the dropdown in the top left, which usually contains the value "main". Select the "tag" that matches your installed version.

NOTE: This action is deprecated since version 1.6.x. Please use the link:../generic-button/GenericButton.adoc[Generic Button.adoc] action. _Deprecated_ means, that this action will not receive any new features, but it will still be supported, and it will not be removed.

== Description

This action is the same as the link:../hotkey/Hotkey.adoc[Hotkey.adoc] action: It sends a keystroke to the active window, and it can be connected to a SimHub property, which will update its state.

The difference is that this action can have up to four states. The logic for the action state in dependency from the SimHub property value is as follows:

- `boolean`: If the property value is `True`, the action will be in the state "1", otherwise in the state "0" state.
- `integer` and `long`: The property value will directly set the state. The value "0" maps to the action state "0", "1" to the action state "1" and so on.

Unlike the action "Hotkey", this action does not support expressions!

Unfortunately, the Stream Deck UI support is very limited for actions which have more than two states. "Title" and icon can only be customized for the first two states. Maybe Stream Deck will enhance their UI one day to allow customization of all states.
